# Generated by Django 2.2.5 on 2019-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190925_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.CharField(default='GENERIC AREA', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.IntegerField(default=3700),
        ),
    ]
