# Generated by Django 2.2.5 on 2019-09-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20190926_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='views',
            field=models.TextField(default=''),
        ),
    ]
